### PR TITLE
pair/tuple defaults

### LINKED ISSUE #711: default value for std::pair
Following code does not work.

```
    // (...)
    float2 pre_translate;
    app.add_option<float2, std::pair<float, float>>(
        "--pre_translate", pre_translate, "translate before scaling (ie. to center the svg file)")
        ->default_val(std::pair<float, float>{0,0});
    // (...)
```

It compiles, but when ran fails with:

```
terminate called after throwing an instance of 'CLI::ArgumentMismatch'
  what():  --pre_translate: At least 2 required but received 1
zsh: IOT instruction (core dumped)  ./a.out --pre_translate 0 0
```

`float2` is interestingly not constructable from `std::pair` but it works nevertheless.
It works correctly if I comment out the `default_val`.

I'm pretty sure I'm doing something wrong. What's the correct method of specifying the default value?

### PR DESCRIPTION
**Pull request by phlptp**
add capability to accept pair/tuple default values and a little cleaner parsing in some cases

Fixes #711

### CODE REVIEW

File: include/CLI/TypeTools.hpp [hunk 1]
```diff
@@ -307,6 +307,30 @@ template <typename S> class is_tuple_like {
     static constexpr bool value = decltype(test<S>(0))::value;
 };
 
+/// This will only trigger for actual void type
```
Comment (phlptp) [inline include/CLI/TypeTools.hpp:310]: code moved to get thing in the right order

File: include/CLI/impl/Option_inl.hpp [hunk 2]
```diff
@@ -662,11 +662,11 @@ CLI11_INLINE std::string Option::_validate(std::string &result, int index) const
 
 CLI11_INLINE int Option::_add_result(std::string &&result, std::vector<std::string> &res) const {
     int result_count = 0;
-    if(allow_extra_args_ && !result.empty() && result.front() == '[' &&
+    if((allow_extra_args_ || get_expected_max() > 1) && !result.empty() && result.front() == '[' &&
        result.back() == ']') {  // this is now a vector string likely from the default or user entry
         result.pop_back();
 
-        for(auto &var : CLI::detail::split(result.substr(1), ',')) {
+        for(auto &var : CLI::detail::split_up(result.substr(1), ',')) {
```
Comment (phlptp) [inline include/CLI/impl/Option_inl.hpp:669]: wasn't handling sub vectors properly

**Comment by phlptp** [comment]
@henryiii   FYI,  no api changes here,  Mainly getting the default_val on parity with the types the options support themselves.   Also cleaned up a few methods.   Was a bug that came up a while ago and hadn't got around to fixing until now.    I will merge in a few days
