### PR TITLE
Version add

### LINKED ISSUE #436: add a version callback similar to help
I am wondering how much use a dedicated version option, like help/help_all/config would be.  It is similar to help in that it should bypass the other error checks and required options.  

I know we end up putting it in most use cases in some way or another,  having it be embedded in CLI11 would standardize and make it easier for everyone.  

I would picture something like
an overload set
```cpp
app.set_version(string version_string);
app.set_version(std::function<std:;string()> version_callback);  
app.set_version(string version_args, string version_string);
app.set_version(string version_args, std::function<std:;string()> version_callback);  
```

this would add a version option ("-v,--version" that triggers a version_exception and is triggered like help does currently.

### PR DESCRIPTION
**Pull request by phlptp**
Add a version operation, similar to config and help, to print out the version and exit.  Supports adding the version via a string or callback.  

We had been doing this in our application and it might seem to be something that is pretty common to want in applications

### CODE REVIEW

File: include/CLI/App.hpp [hunk 1]
```diff
@@ -703,6 +706,56 @@ class App {
...
+                [vfunc]() { throw(CLI::CallForVersion(vfunc(), 0)); },
+                "display program version information and exit");
+            version_ptr_->configurable(false);
+        }
+
+        return version_ptr_;
+    }
+    /// Set the version as a string
+    App *version(const std::string &versionString) {
+        set_version_flag("-v,--version", versionString);
```
Comment (nightlark) [inline include/CLI/App.hpp]: `-v` is commonly also used for verbose by programs (including cp, rm, wget, curl, mv).

Comment (jzakrzewski) [reply include/CLI/App.hpp]: So is `-V` basically it's a guess which one will be equivalent to `--version` and which to `--verbose`. Each default is equally good/bad.

Comment (phlptp) [reply include/CLI/App.hpp]: ok, I removed the "-v" from the default since it seems that could mean any number of different things from common applications.

**Comment by phlptp** [comment]
closes #436

**Comment by henryiii** [comment]
I am not really sure we need to have the `version` shortcut. It only adds the "--version" for you - which I was going to consider suggesting as an argument, but then that's exactly what `set_version_flag` is. There's also some ambiguity in whether it is setting the version or accessing the version (which is not needed, but it's not completely clear). Thoughts?

**Comment by phlptp** [comment]
I am fine removing it, hadn't thought about the ambiguity on whether it would be accessing the version.

**Comment by phlptp** [comment]
Do we want to keep the `std::string version() const` operation?

**Comment by henryiii** [comment]
No (I'd missed that, actually), but that's what I would expect "version()" to do; the dual use might be also a bit confusing.

**Comment by phlptp** [comment]
removed all `version`  methods

**Comment by henryiii** [comment]
I'm sorry, I meant "Yes, we could keep it" - somehow I stared with No then (I think) explained why we should keep it. I was just saying that version() returning a string and version(string) could possibly be confusing, so it was another reason that it might be nice to remove version(string).

**Comment by phlptp** [comment]
ok, I will that one back in :)

**Review by henryiii — APPROVED** [review]
